import {Section} from "./FlashcardGame";


export const flashcardData: Section[] = [
  {
    section: "Lotnisko",
    words: [
      { pl: "odprawa", en: "check-in" },
      { pl: "dowód osobisty", en: "id card" },
      { pl: "bilet", en: "ticket" },
      { pl: "bramka", en: "gate" },
      { pl: "wchodzenie na pokład", en: "boarding" },
      { pl: "karta pokładowa", en: "boarding pass" },
      { pl: "czas wejścia na pokład samolotu", en: "boarding time" },
      { pl: "stanowisko odpraw", en: "check-in counter" },
      { pl: "kontrola paszportowa", en: "passport control" },
      { pl: "kontrola bezpieczeństwa", en: "security check" },
      { pl: "kontrola celna", en: "customs" },
      { pl: "odbiór bagażu", en: "luggage / baggage claim" },
      { pl: "walizka", en: "suitcase" },
      { pl: "plecak", en: "backpack" },
      { pl: "teczka", en: "briefcase" },
      { pl: "torba", en: "bag" },
      { pl: "bagaż", en: "luggage" },
      { pl: "bagaż podręczny", en: "carry-on luggage" },
      { pl: "odlot", en: "departure" },
      { pl: "przylot", en: "arrival" },
      { pl: "odwołany", en: "cancelled" },
      { pl: "opóźniony", en: "delayed" },
      { pl: "lot z przesiadką", en: "connecting flight" },
      { pl: "lot bezpośredni", en: "direct flight" },
      { pl: "przesiadka/postój", en: "layover/stopover" },
      { pl: "winda", en: "elevator" },
      { pl: "schody ruchome", en: "escalators" },
      { pl: "toalety", en: "toilets" },
      { pl: "sklep bezcłowy", en: "duty-free shop" },
      { pl: "rozkład lotów", en: "flight schedules" },
      { pl: "hala odlotów", en: "departure lounge" },
      { pl: "taśma", en: "carousel" },
      { pl: "gratisowy", en: "complimentary" },
      { pl: "delikatny", en: "fragile" },
      { pl: "za ciężki", en: "too heavy" },
      { pl: "przedmioty zabronione", en: "prohibited items" },
    ],
    expressions: [
      { pl: "proszę przejść...", en: "please, proceed..." },
      { pl: "czy ma pani/pan coś do oclenia?", en: "do you have anything to declare?" },
      { pl: "ile masz sztuk bagażu?", en: "how many pieces of luggage do you have?" },
      { pl: "czy masz przy sobie jakieś płyny?", en: "are you traveling with any liquids?" },
      { pl: "czy przewozisz jakieś paczki?", en: "are you carrying any parcels?" },
      { pl: "celem mojej wizyty jest...", en: "purpose of my visit is..." },
      { pl: "podróżuję w celach wypoczynkowych", en: "I am travelling for leisure" },
      { pl: "będę tu przez…", en: "I will be here for…" },
      { pl: "zatrzymam się w…", en: "I am staying at…" },
      { pl: "mam tylko jedną torbę podręczną", en: "I have just one carry-on bag" },
      { pl: "gdzie mogę odebrać bagaż?", en: "where’s the baggage reclaim?" },
    ],
  },
  {
    section: "Samolot",
    words: [
      { pl: "schowek na bagaż podręczny", en: "overhead compartment" },
      { pl: "miejsce przy przejściu", en: "aisle seat" },
      { pl: "miejsce przy oknie", en: "window seat" },
      { pl: "zamienić się miejscami", en: "switch seats" },
      { pl: "stolik składany", en: "tray table" },
      { pl: "instrukcje bezpieczeństwa", en: "safety instructions" },
      { pl: "wyjście awaryjne", en: "emergency exit" },
      { pl: "zasłonka na okno", en: "window shade" },
      { pl: "odchylić fotel", en: "recline the seat" },
      { pl: "wyłączyć urządzenia elektroniczne", en: "turn off electronic devices" },
      { pl: "zająć swoje miejsca", en: "take seats" },
      { pl: "zapiąć pasy", en: "fasten seat belts" },
      { pl: "steward/stewardesa", en: "flight attendant" },
    ],
    expressions: [
      { pl: "mógłbyś mi powiedzieć…", en: "could you tell me…" },
      { pl: "chciałbym dowiedzieć się…", en: "I would like to know…" },
      { pl: "słucham?", en: "pardon?" },
      { pl: "słucham?", en: "sorry?" },
      { pl: "słucham?", en: "excuse me?" },
      { pl: "czy możesz powtórzyć?", en: "can you repeat, please?" },
      { pl: "możesz powiedzieć to jeszcze raz?", en: "can you say that again?" },
    ],
  },
  {
    section: "Transport",
    words: [
      { pl: "dworzec kolejowy", en: "train station" },
      { pl: "dworzec autobusowy", en: "bus station" },
      { pl: "metro", en: "underground" },
      { pl: "przesiadka", en: "connection" },
      { pl: "peron", en: "platform" },
      { pl: "opóźnienie", en: "delay" },
      { pl: "rozkład jazdy", en: "schedule" },
      { pl: "kasa", en: "ticket office" },
      { pl: "automaty biletowe", en: "ticket machines" },
      { pl: "wsiąść do pociągu", en: "take the train" },
      { pl: "wsiąść do autobusu", en: "take the bus" },
      { pl: "bilet w jedną stronę", en: "one-way ticket" },
      { pl: "bilet powrotny", en: "return ticket" },
      { pl: "pociąg podmiejski", en: "commuter train" },
      { pl: "pociąg dalekobieżny", en: "long-distance train" },
      { pl: "wagon", en: "carriage" },
      { pl: "przedział", en: "compartment" },
      { pl: "półka na bagaż", en: "luggage rack" },
    ],
    expressions: [
      { pl: "pociąg nadjedzie za…", en: "train will be arriving in…" },
      { pl: "bus odjeżdża z…", en: "bus departs from…" },
      { pl: "poproszę bilet", en: "I would like a ticket" },
      { pl: "chciałbym kupić bilet do…", en: "I would like to buy a ticket to…." },
      { pl: "o której godzinie przyjeżdża do…?", en: "what time does it reach…?" },
      { pl: "czy mógłbym prosić pana bilet?", en: "can I see your ticket, please?" },
    ],
  },
  {
    section: "Droga",
    words: [
      { pl: "chodnik", en: "sidewalk" },
      { pl: "przejście dla pieszych", en: "crosswalk" },
      { pl: "skrót", en: "shortcut" },
      { pl: "przejście podziemne", en: "underpass" },
      { pl: "wiadukt", en: "overpass" },
      { pl: "centrum miasta", en: "downtown" },
      { pl: "światła", en: "traffic lights" },
      { pl: "rondo", en: "roundabout" },
    ],
    expressions: [
      { pl: "idź prosto", en: "go straight ahead" },
      { pl: "idź tą ulicą", en: "go along the street" },
      { pl: "miejsce niedaleko na tej samej ulicy", en: "place down the street" },
      { pl: "tuż za rogiem", en: "right around the corner" },
      { pl: "skręć w drugą w prawo", en: "take the second turning on the right" },
      { pl: "przepraszam, czy wiesz, gdzie jest...?", en: "excuse me, do you know where the... is?" },
      { pl: "jak dostać się do…", en: "how to get to…" },
      { pl: "jak daleko…", en: "how far…" },
    ],
  },
  {
    section: "Hotel",
    words: [
      { pl: "zameldowanie", en: "check-in" },
      { pl: "wymeldowanie", en: "check-out" },
      { pl: "paragon", en: "receipt" },
      { pl: "kaucja", en: "deposit" },
      { pl: "recepcja", en: "front desk / reception desk" },
      { pl: "lobby, hall", en: "lobby" },
      { pl: "pokój jednoosobowy", en: "single room" },
      { pl: "pokój dwuosobowy", en: "double room" },
      { pl: "pokój dwuosobowy (pojedyncze łóżka)", en: "twin room" },
      { pl: "wolne miejsce", en: "vacancy" },
      { pl: "brak wolnych miejsc", en: "no vacancies" },
      { pl: "zakwaterowanie", en: "accommodation" },
      { pl: "pościel", en: "linen" },
      { pl: "ręczniki", en: "towels" },
      { pl: "winda", en: "elevator" },
      { pl: "klimatyzacja", en: "air conditioning" },
      { pl: "obsługa hotelowa", en: "room service" },
      { pl: "usługa prania", en: "laundry service" },
      { pl: "nie przeszkadzać", en: "do not disturb" },
      { pl: "dwa tygodnie", en: "a fortnight" },
      { pl: "udogodnienia, wyposażenie", en: "amenities" },
      { pl: "dodatkowa opłata za wymeldowanie się po czasie", en: "late charge" },
      { pl: "kierownik hotelu", en: "hotel manager" },
      { pl: "pokojówka, obsługa hotelu", en: "housekeeping, maid" },
    ],
    expressions: [
      { pl: "chciałbym zrobić rezerwację", en: "I would like to make a reservation" },
      { pl: "chciałbym zarezerwować pokój", en: "I’d like to book a room" },
      { pl: "mam rezerwację na nazwisko…", en: "I have a reservation under the name of…" },
      { pl: "jak mam połączyć się z wi-fi?", en: "how do I get on the wifi?" },
      { pl: "czy śniadanie jest wliczone w cenę?", en: "is breakfast included?" },
      { pl: "o której podawane jest śniadanie?", en: "when do you serve breakfast?" },
      { pl: "czy jest darmowe wi-fi?", en: "is there free wifi?" },
      { pl: "czy mogę gdzieś tutaj zostawić bagaże?", en: "is there somewhere I can leave my luggage?" },
      { pl: "na którym piętrze znajduje się …?", en: "what floor is … on?" },
      { pl: "chcielibyśmy się wymeldować", en: "we would like to check-out" },
      { pl: "nasz pobyt tutaj był przyjemny", en: "we enjoyed our stay" },
    ],
  },
  {
    section: "Restauracja",
    words: [
      { pl: "płacić gotówką", en: "pay cash" },
      { pl: "płacić kartą", en: "pay by card" },
      { pl: "zostawić napiwek", en: "leave the tip" },
      { pl: "zarezerwowane", en: "reserved" },
      { pl: "stolik dla dwóch osób", en: "table for two" },
      { pl: "rezerwacja na nazwisko...", en: "reservation under the name of…" },
      { pl: "kelner/kelnerka", en: "waiter/waitress" },
      { pl: "serwetka", en: "a napkin" },
      { pl: "nóż", en: "knife" },
      { pl: "widelec", en: "fork" },
      { pl: "łyżka", en: "spoon" },
      { pl: "zestaw sztućców", en: "set of cutlery" },
      { pl: "pałeczki", en: "chopsticks" },
    ],
    expressions: [
      { pl: "mam rezerwację", en: "I have a reservation" },
      { pl: "jak długo trzeba czekać?", en: "how long is the wait?" },
      { pl: "czy możemy tu usiąść?", en: "can we sit here?" },
      { pl: "czy ten stolik jest wolny?", en: "is that table available?" },
      { pl: "czy mogę prosić o menu", en: "I would like to see menu, please" },
      { pl: "czy mogę zobaczyć menu?", en: "can I see the menu?" },
      { pl: "przepraszam!", en: "excuse me!" },
      { pl: "chcielibyśmy zamówić", en: "we are ready to order" },
      { pl: "chciałbym/chciałabym…", en: "I'd like…" },
      { pl: "dla mnie…", en: "for me…" },
      { pl: "co pan poleca", en: "what do you recommend" },
      { pl: "czy moglibyśmy prosić o rachunek", en: "could we have our bill please" },
      { pl: "czy moglibyśmy prosić o rachunek", en: "could we have the check please" },
      { pl: "czy można już przyjąć zamówienie", en: "are you ready to order" },
      { pl: "czy podać państwu jakieś sosy?", en: "would you like any sauces?" },
      { pl: "smacznego", en: "enjoy your meal" },
    ],
  },
  {
    section: "Jedzenie",
    words: [
      { pl: "słodkie", en: "sweet" },
      { pl: "słone", en: "salty" },
      { pl: "gorzkie", en: "bitter" },
      { pl: "kwaśne", en: "sour" },
      { pl: "ostre", en: "spicy" },
      { pl: "łagodne", en: "mild" },
      { pl: "mdłe", en: "bland" },
      { pl: "dolewka (napoju)", en: "refill" },
      { pl: "woda z kranu", en: "tap water" },
      { pl: "niegazowana czy gazowana", en: "still or sparkling" },
      { pl: "przystawki", en: "starters" },
      { pl: "przystawki", en: "appetizers" },
      { pl: "lżejsze dania", en: "lighter dishes" },
      { pl: "zupy", en: "soups" },
      { pl: "sałatki", en: "salads" },
      { pl: "zawijasy", en: "wraps" },
      { pl: "kanapki", en: "panini / sandwiches" },
      { pl: "burgery", en: "burgers" },
      { pl: "kanapki w chlebku pita", en: "pittas" },
      { pl: "makarony", en: "pastas" },
      { pl: "wybór przekąsek do wspólnego spożycia", en: "platters to share" },
      { pl: "dania główne", en: "mains" },
      { pl: "dania mięsne", en: "meat" },
      { pl: "owoce morza", en: "seafood" },
      { pl: "dodatki", en: "sides" },
      { pl: "napoje", en: "drinks" },
      { pl: "desery", en: "desserts" },
      { pl: "z pieca", en: "baked" },
      { pl: "smażony w cieście", en: "battered" },
      { pl: "gotowany", en: "boiled" },
      { pl: "duszony", en: "braised" },
      { pl: "kandyzowany", en: "candied" },
      { pl: "karmelizowany", en: "caramelized" },
      { pl: "drobno pokrojony", en: "chopped" },
      { pl: "chrupiący", en: "crunchy" },
      { pl: "pokrojony w kostkę", en: "diced" },
      { pl: "filetowany", en: "filleted" },
      { pl: "smażony", en: "fried" },
      { pl: "grillowany", en: "grilled" },
      { pl: "mielony", en: "ground / minced" },
      { pl: "gotowany/pieczony powoli", en: "pulled" },
      { pl: "surowy", en: "raw" },
      { pl: "pieczony", en: "roasted" },
      { pl: "sauté (podsmażany na małej ilości tłuszczu)", en: "sautéed" },
      { pl: "wędzony", en: "smoked" },
      { pl: "na parze", en: "steamed" },
      { pl: "faszerowany", en: "stuffed" }
    ],
    expressions: []
  },
  {
    section: "Zakupy",
    words: [
      { pl: "płacić kartą", en: "pay by card" },
      { pl: "płacić gotówką", en: "pay in cash" },
      { pl: "terminal płatniczy", en: "credit card reader" },
      { pl: "przymierzalnia", en: "fitting room" },
      { pl: "paragon", en: "receipt" },
      { pl: "w promocji", en: "on sale" },
      { pl: "zniżka", en: "discount" },
      { pl: "metka", en: "price tag" }
    ],
    expressions: [
      { pl: "dziękuję, tylko oglądam", en: "I'm just looking, thank you" },
      { pl: "szukam…", en: "I’m looking for…" },
      { pl: "chcę kupić…", en: "I want to buy…" },
      { pl: "jestem zainteresowany…", en: "I am interested in…" },
      { pl: "czy macie… ?", en: "do you have… ?" },
      { pl: "poproszę…", en: "I’d like…" },
      { pl: "biorę", en: "I’ll take it" },
      { pl: "ile kosztuje…", en: "how much is…" },
      { pl: "ile to będzie kosztować", en: "how much does it cost" },
      { pl: "ile to razem będzie?", en: "how much that will be?" }
    ]
  }
]